from datetime import datetime, timezone
from sqlalchemy import DateTime, Boolean, Enum as SAEnum, Float, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..base import Base
from .enums import *
def now(): return datetime.now(timezone.utc)
class User(Base):
 __tablename__='users'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(100),nullable=False); email:Mapped[str]=mapped_column(String(255),unique=True,nullable=False,index=True); password_hash:Mapped[str]=mapped_column(String(255),nullable=False); role:Mapped[UserRole]=mapped_column(SAEnum(UserRole,native_enum=False),default=UserRole.STUDENT,nullable=False,index=True); is_active:Mapped[bool]=mapped_column(Boolean,default=True,nullable=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False)
 student_profile=relationship('StudentProfile',back_populates='user',uselist=False,cascade='all, delete-orphan')
class StudentProfile(Base):
 __tablename__='student_profiles'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id',ondelete='CASCADE'),unique=True,nullable=False,index=True); college:Mapped[str|None]=mapped_column(String(200)); degree:Mapped[str|None]=mapped_column(String(150)); branch:Mapped[str|None]=mapped_column(String(150)); graduation_year:Mapped[int|None]=mapped_column(Integer,index=True); semester:Mapped[int|None]=mapped_column(Integer); cgpa:Mapped[float|None]=mapped_column(Float); location:Mapped[str|None]=mapped_column(String(150),index=True); career_interest:Mapped[str|None]=mapped_column(String(200)); preferred_location:Mapped[str|None]=mapped_column(String(150)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False)
 user=relationship('User',back_populates='student_profile'); academic_records=relationship('AcademicRecord',back_populates='student',cascade='all, delete-orphan'); student_skills=relationship('StudentSkill',back_populates='student',cascade='all, delete-orphan'); resumes=relationship('Resume',back_populates='student',cascade='all, delete-orphan'); roadmaps=relationship('Roadmap',back_populates='student',cascade='all, delete-orphan'); interview_sessions=relationship('InterviewSession',back_populates='student',cascade='all, delete-orphan'); recommendations=relationship('Recommendation',back_populates='student',cascade='all, delete-orphan')
class AcademicRecord(Base):
 __tablename__='academic_records'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); qualification:Mapped[str]=mapped_column(String(100),nullable=False,index=True); institution:Mapped[str]=mapped_column(String(200),nullable=False,index=True); field_of_study:Mapped[str|None]=mapped_column(String(150)); percentage_or_cgpa:Mapped[float|None]=mapped_column(Float); start_year:Mapped[int|None]=mapped_column(Integer); end_year:Mapped[int|None]=mapped_column(Integer); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); student=relationship('StudentProfile',back_populates='academic_records')
class Skill(Base):
 __tablename__='skills'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(100),unique=True,nullable=False,index=True); category:Mapped[str|None]=mapped_column(String(100),index=True); description:Mapped[str|None]=mapped_column(Text); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); student_skills=relationship('StudentSkill',back_populates='skill'); career_skills=relationship('CareerSkill',back_populates='skill'); roadmap_items=relationship('RoadmapItem',back_populates='skill')
class StudentSkill(Base):
 __tablename__='student_skills'; __table_args__=(UniqueConstraint('student_id','skill_id',name='uq_student_skill'),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); skill_id:Mapped[int]=mapped_column(ForeignKey('skills.id',ondelete='RESTRICT'),nullable=False,index=True); proficiency_level:Mapped[ProficiencyLevel]=mapped_column(SAEnum(ProficiencyLevel,native_enum=False),nullable=False,index=True); source:Mapped[SkillSource]=mapped_column(SAEnum(SkillSource,native_enum=False),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); student=relationship('StudentProfile',back_populates='student_skills'); skill=relationship('Skill',back_populates='student_skills')
class Career(Base):
 __tablename__='careers'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); title:Mapped[str]=mapped_column(String(150),unique=True,nullable=False,index=True); description:Mapped[str|None]=mapped_column(Text); industry:Mapped[str|None]=mapped_column(String(100),index=True); demand_level:Mapped[DemandLevel|None]=mapped_column(SAEnum(DemandLevel,native_enum=False),index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); career_skills=relationship('CareerSkill',back_populates='career',cascade='all, delete-orphan'); roadmaps=relationship('Roadmap',back_populates='career'); interview_sessions=relationship('InterviewSession',back_populates='career'); recommendations=relationship('Recommendation',back_populates='career')
class CareerSkill(Base):
 __tablename__='career_skills'; __table_args__=(UniqueConstraint('career_id','skill_id',name='uq_career_skill'),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True); career_id:Mapped[int]=mapped_column(ForeignKey('careers.id',ondelete='CASCADE'),nullable=False,index=True); skill_id:Mapped[int]=mapped_column(ForeignKey('skills.id',ondelete='RESTRICT'),nullable=False,index=True); importance:Mapped[SkillImportance]=mapped_column(SAEnum(SkillImportance,native_enum=False),nullable=False,index=True); minimum_level:Mapped[ProficiencyLevel]=mapped_column(SAEnum(ProficiencyLevel,native_enum=False),nullable=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); career=relationship('Career',back_populates='career_skills'); skill=relationship('Skill',back_populates='career_skills')
class Course(Base):
 __tablename__='courses'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); title:Mapped[str]=mapped_column(String(200),nullable=False); provider:Mapped[str]=mapped_column(String(150),nullable=False,index=True); description:Mapped[str|None]=mapped_column(Text); url:Mapped[str|None]=mapped_column(String(500)); level:Mapped[LearningLevel|None]=mapped_column(SAEnum(LearningLevel,native_enum=False),index=True); duration:Mapped[str|None]=mapped_column(String(100)); price_type:Mapped[PriceType]=mapped_column(SAEnum(PriceType,native_enum=False),default=PriceType.UNKNOWN,nullable=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); recommendations=relationship('Recommendation',back_populates='course')
class Certification(Base):
 __tablename__='certifications'; __table_args__=(UniqueConstraint('name','provider',name='uq_certification_provider'),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True); name:Mapped[str]=mapped_column(String(200),nullable=False); provider:Mapped[str]=mapped_column(String(150),nullable=False,index=True); description:Mapped[str|None]=mapped_column(Text); url:Mapped[str|None]=mapped_column(String(500)); level:Mapped[LearningLevel|None]=mapped_column(SAEnum(LearningLevel,native_enum=False),index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); recommendations=relationship('Recommendation',back_populates='certification')
class Resume(Base):
 __tablename__='resumes'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); file_name:Mapped[str]=mapped_column(String(255),nullable=False); file_path:Mapped[str]=mapped_column(String(500),nullable=False); file_type:Mapped[ResumeFileType]=mapped_column(SAEnum(ResumeFileType,native_enum=False),nullable=False); extracted_text:Mapped[str|None]=mapped_column(Text); analysis_status:Mapped[AnalysisStatus]=mapped_column(SAEnum(AnalysisStatus,native_enum=False),default=AnalysisStatus.PENDING,nullable=False,index=True); uploaded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False,index=True); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False); student=relationship('StudentProfile',back_populates='resumes')
class Opportunity(Base):
 __tablename__='opportunities'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); title:Mapped[str]=mapped_column(String(200),nullable=False); organization:Mapped[str]=mapped_column(String(200),nullable=False,index=True); opportunity_type:Mapped[OpportunityType]=mapped_column(SAEnum(OpportunityType,native_enum=False),nullable=False,index=True); description:Mapped[str|None]=mapped_column(Text); location:Mapped[str|None]=mapped_column(String(150),index=True); eligibility:Mapped[str|None]=mapped_column(Text); application_url:Mapped[str|None]=mapped_column(String(500)); deadline:Mapped[datetime|None]=mapped_column(DateTime(timezone=True),index=True); source:Mapped[str|None]=mapped_column(String(200),index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); recommendations=relationship('Recommendation',back_populates='opportunity')
class Roadmap(Base):
 __tablename__='roadmaps'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); career_id:Mapped[int]=mapped_column(ForeignKey('careers.id',ondelete='RESTRICT'),nullable=False,index=True); title:Mapped[str]=mapped_column(String(200),nullable=False); description:Mapped[str|None]=mapped_column(Text); status:Mapped[RoadmapStatus]=mapped_column(SAEnum(RoadmapStatus,native_enum=False),default=RoadmapStatus.ACTIVE,nullable=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now,nullable=False); student=relationship('StudentProfile',back_populates='roadmaps'); career=relationship('Career',back_populates='roadmaps'); items=relationship('RoadmapItem',back_populates='roadmap',cascade='all, delete-orphan')
class RoadmapItem(Base):
 __tablename__='roadmap_items'; __table_args__=(UniqueConstraint('roadmap_id','sequence',name='uq_roadmap_sequence'),)
 id:Mapped[int]=mapped_column(Integer,primary_key=True); roadmap_id:Mapped[int]=mapped_column(ForeignKey('roadmaps.id',ondelete='CASCADE'),nullable=False,index=True); skill_id:Mapped[int|None]=mapped_column(ForeignKey('skills.id',ondelete='RESTRICT'),index=True); title:Mapped[str]=mapped_column(String(200),nullable=False); description:Mapped[str|None]=mapped_column(Text); sequence:Mapped[int]=mapped_column(Integer,nullable=False); status:Mapped[RoadmapItemStatus]=mapped_column(SAEnum(RoadmapItemStatus,native_enum=False),default=RoadmapItemStatus.NOT_STARTED,nullable=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); roadmap=relationship('Roadmap',back_populates='items'); skill=relationship('Skill',back_populates='roadmap_items')
class InterviewSession(Base):
 __tablename__='interview_sessions'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); career_id:Mapped[int|None]=mapped_column(ForeignKey('careers.id',ondelete='SET NULL'),index=True); session_type:Mapped[InterviewType]=mapped_column(SAEnum(InterviewType,native_enum=False),nullable=False,index=True); overall_score:Mapped[float|None]=mapped_column(Float); feedback:Mapped[str|None]=mapped_column(Text); started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False,index=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); student=relationship('StudentProfile',back_populates='interview_sessions'); career=relationship('Career',back_populates='interview_sessions'); answers=relationship('InterviewAnswer',back_populates='session',cascade='all, delete-orphan')
class InterviewAnswer(Base):
 __tablename__='interview_answers'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); session_id:Mapped[int]=mapped_column(ForeignKey('interview_sessions.id',ondelete='CASCADE'),nullable=False,index=True); question:Mapped[str]=mapped_column(Text,nullable=False); answer:Mapped[str|None]=mapped_column(Text); feedback:Mapped[str|None]=mapped_column(Text); score:Mapped[float|None]=mapped_column(Float,index=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False,index=True); session=relationship('InterviewSession',back_populates='answers')
class Recommendation(Base):
 __tablename__='recommendations'
 id:Mapped[int]=mapped_column(Integer,primary_key=True); student_id:Mapped[int]=mapped_column(ForeignKey('student_profiles.id',ondelete='CASCADE'),nullable=False,index=True); recommendation_type:Mapped[RecommendationType]=mapped_column(SAEnum(RecommendationType,native_enum=False),nullable=False,index=True); career_id:Mapped[int|None]=mapped_column(ForeignKey('careers.id',ondelete='SET NULL'),index=True); course_id:Mapped[int|None]=mapped_column(ForeignKey('courses.id',ondelete='SET NULL'),index=True); certification_id:Mapped[int|None]=mapped_column(ForeignKey('certifications.id',ondelete='SET NULL'),index=True); opportunity_id:Mapped[int|None]=mapped_column(ForeignKey('opportunities.id',ondelete='SET NULL'),index=True); title:Mapped[str]=mapped_column(String(200),nullable=False); explanation:Mapped[str|None]=mapped_column(Text); score:Mapped[float|None]=mapped_column(Float,index=True); source:Mapped[str|None]=mapped_column(String(200)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,nullable=False); student=relationship('StudentProfile',back_populates='recommendations'); career=relationship('Career',back_populates='recommendations'); course=relationship('Course',back_populates='recommendations'); certification=relationship('Certification',back_populates='recommendations'); opportunity=relationship('Opportunity',back_populates='recommendations')
