from enum import Enum
class UserRole(str,Enum): STUDENT='student'; ADMIN='admin'
class ProficiencyLevel(str,Enum): BEGINNER='beginner'; INTERMEDIATE='intermediate'; ADVANCED='advanced'; EXPERT='expert'
class SkillSource(str,Enum): PROFILE='profile'; RESUME='resume'; ASSESSMENT='assessment'; AI_EXTRACTED='ai_extracted'
class DemandLevel(str,Enum): LOW='low'; MEDIUM='medium'; HIGH='high'
class SkillImportance(str,Enum): OPTIONAL='optional'; USEFUL='useful'; IMPORTANT='important'; ESSENTIAL='essential'
class LearningLevel(str,Enum): BEGINNER='beginner'; INTERMEDIATE='intermediate'; ADVANCED='advanced'
class PriceType(str,Enum): FREE='free'; PAID='paid'; FREEMIUM='freemium'; UNKNOWN='unknown'
class ResumeFileType(str,Enum): PDF='pdf'; DOCX='docx'
class AnalysisStatus(str,Enum): PENDING='pending'; PROCESSING='processing'; COMPLETED='completed'; FAILED='failed'
class OpportunityType(str,Enum): JOB='job'; INTERNSHIP='internship'; GOVERNMENT='government'
class RoadmapStatus(str,Enum): ACTIVE='active'; COMPLETED='completed'; ARCHIVED='archived'
class RoadmapItemStatus(str,Enum): NOT_STARTED='not_started'; IN_PROGRESS='in_progress'; COMPLETED='completed'
class InterviewType(str,Enum): GENERAL='general'; TECHNICAL='technical'; HR='hr'; BEHAVIORAL='behavioral'
class RecommendationType(str,Enum): CAREER='career'; COURSE='course'; CERTIFICATION='certification'; OPPORTUNITY='opportunity'; SKILL='skill'
